### ISSUE TITLE
data api: iterating over results by label fails with unknown error

### ISSUE THREAD

**Issue by tomhanoldt** [serverless/cloud#177]
When iterating over results of a query by label an unknown error is thrown:
- if it is intended that label responses cannot be iterated, the documentation should be adjusted and the input parameters checked
- otherwise this is a bug

```typescript
import { data, GetResponse } from '@serverless/cloud'

const testData = [
  { key: 'key:1', label1: 'label:1', value: '1' },
  { key: 'key:2', label1: 'label:2', value: '2' },
  { key: 'key:3', label1: 'label:3', value: '3' },
]

async function test() {
  for (const dataset of testData) {
    await data.set(dataset.key, dataset.value, { label1: dataset.label1 })
  }

  console.log('starting test - resultByKey')
  let resultByKey: GetResponse<unknown> | null = await data.get('key:*', {
    limit: 1,
  })
  while (resultByKey) {
    console.log('resultByKey', resultByKey)
    resultByKey = resultByKey.next ? await resultByKey.next() : null
  }

  console.log('starting test - resultByLabel')
  // let resultByLabel: GetResponse<unknown> | null = await data.get('label:*', {
  //   label: 'label1' as labels,
  //   limit: 1,
  // })
  let resultByLabel: GetResponse<unknown> | null = await data.getByLabel(
    'label1',
    'label:*',
    {
      limit: 1,
    }
  )
  while (resultByLabel) {
    console.log('resultByLabel', resultByLabel)
    resultByLabel = resultByLabel.next ? await resultByLabel.next() : null
  }
}

test()
```

results in:
```
13:29:34 ─ starting test - resultByKey
13:29:34 ─ resultByKey {
  items: [ { key: 'key:1', value: '1' } ],
  lastKey: 'key:1',
  next: [Function: next]
}
13:29:34 ─ resultByKey {
  items: [ { key: 'key:2', value: '2' } ],
  lastKey: 'key:2',
  next: [Function: next]
}
13:29:34 ─ resultByKey { items: [ { key: 'key:3', value: '3' } ] }
13:29:34 ─ starting test - resultByLabel
13:29:34 ─ resultByLabel {
  items: [ { key: 'key:1', value: '1' } ],
  lastKey: 'key:1',
  next: [Function: next]
}
13:29:35 ─ /opt/nodejs/cloud/public.cjs:146

13:29:35 ─ `+(o!==s?`result of cast: ${o}`:""))}return i}_cast(t,n){let r=t===void 0?t:this.transforms.reduce((i,s)=>s.call(this,i,t,this),t);return r===void 0&&(r=this.getDefault()),r}_validate(t,n={},r)
[...]
 s-maxage=${qu.MAX_AGE}, must-revalidate`),a.pipe(n);return}}r()}}get application(){return this.app}},qf=qu;qf.MAX_AGE=60*60*24;var b5n='<!DOCTYPE html><html lang="en"><head><title>Not found</title></head><body><main><h1>Not found</h1></main></body></html>',S5n=`

13:29:35 ─ Error: An unknown error has occurred.

13:29:35 ─ at Ud (/lib/data/src/index.ts:226:13)

13:29:35 ─ at runMicrotasks (<anonymous>)

13:29:35 ─ at processTicksAndRejections (node:internal/process/task_queues:96:5)

13:29:35 ─ at test (file:///tmp/task/src/file:/tmp/task/src/application.ts:37:42)
```

**Comment by tomhanoldt** [comment]
even iterating manually throws the unknown error
```
import { data, GetResponse } from '@serverless/cloud'

const testData = [
  { key: 'key:1', label1: 'label:1', value: '1' },
  { key: 'key:2', label1: 'label:2', value: '2' },
  { key: 'key:3', label1: 'label:3', value: '3' },
]

async function test() {
  for (const dataset of testData) {
    await data.set(dataset.key, dataset.value, { label1: dataset.label1 })
  }

  console.log('starting test - resultByKey')
  let resultByKey: GetResponse<unknown> | null = await data.get('key:*', {
    limit: 1,
  })
  while (resultByKey) {
    console.log('resultByKey', resultByKey)
    if (resultByKey.lastKey)
      resultByKey = await data.get('key:*', {
        limit: 1,
        start: resultByKey.lastKey,
      })
    else resultByKey = null
  }

  console.log('starting test - resultByLabel')
  let resultByLabel: GetResponse<unknown> | null = await data.getByLabel(
    'label1',
    'label:*',
    {
      limit: 1,
    }
  )
  while (resultByLabel) {
    console.log('resultByLabel', resultByLabel)
    if (resultByLabel.lastKey)
      resultByLabel = await data.getByLabel('label1', 'label:*', {
        limit: 1,
        start: resultByLabel.lastKey,
      })
    else resultByLabel = null
  }
}

test()
```

**Comment by tomhanoldt** [comment]
sorry - reopen ^^

**Comment by emrahssamdan** [comment]
Hi @tomhanoldt, we are currently working on the problem and will let you know when we have the fix available. Sorry for the situation.

**Comment by emrahssamdan** [comment]
Hi @tomhanoldt, this should be resolved now. Could you please check and confirm that it's working for you? Thanks for the heads up!

**Comment by tomhanoldt** [comment]
Great! @emrahssamdan - specs are green now 💯  - thank you and the team a lot 👍

**Comment by tomhanoldt** [comment]
unfortunately i have to reopen the issue, since today the error case occurs again

**Comment by benminer** [comment]
> unfortunately i have to reopen the issue @emrahssamdan - since today the error case occurs again but with an other error thrown
> 
> `Error: Pass options.removeUndefinedValues=true to remove undefined values from map/array/set.`

Will fix this, thanks for the callout.

**Comment by benminer** [comment]
> unfortunately i have to reopen the issue @emrahssamdan - since today the error case occurs again but with an other error thrown
> 
> `Error: Pass options.removeUndefinedValues=true to remove undefined values from map/array/set.`

@tomhanoldt Were you getting this on `set` calls or `getByLabel` calls?

**Comment by tomhanoldt** [comment]
by label calls when running this code for example:

```
import { data, GetResponse } from '@serverless/cloud'

const testData = [
  { key: 'key:1', label1: 'label:1', value: '1' },
  { key: 'key:2', label1: 'label:2', value: '2' },
  { key: 'key:3', label1: 'label:3', value: '3' },
]

async function test() {
  for (const dataset of testData) {
    await data.set(dataset.key, dataset.value, { label1: dataset.label1 })
  }

  console.log('starting test - resultByKey')
  let resultByKey: GetResponse<unknown> | null = await data.get('key:*', {
    limit: 1,
  })
  while (resultByKey) {
    console.log('resultByKey', resultByKey)
    if (resultByKey.lastKey)
      resultByKey = await data.get('key:*', {
        limit: 1,
        start: resultByKey.lastKey,
      })
    else resultByKey = null
  }

  console.log('starting test - resultByLabel')
  let resultByLabel: GetResponse<unknown> | null = await data.getByLabel(
    'label1',
    'label:*',
    {
      limit: 1,
    }
  )
  while (resultByLabel) {
    console.log('resultByLabel', resultByLabel)
    if (resultByLabel.lastKey)
      resultByLabel = await data.getByLabel('label1', 'label:*', {
        limit: 1,
        start: resultByLabel.lastKey,
      })
    else resultByLabel = null
  }
}

test()
```

**Comment by tomhanoldt** [comment]
It was a fault on my side, sorry - but maybe you could improve the documentation and add a check when storing an item:
- accidently I added two `:` colons as a namespaces for a label key and was able to write it to the data store
- when trying to read that item it failed

...but why the examplem above failed I dont know
